In [3]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

In [4]:
# customizing 'markdown' font style
from IPython.display import display, HTML

display(HTML("""
<style>
.jp-RenderedMarkdown{
    color: red !important;
    font-size: 28px !important;
    font-weight: 700 !important;
}
</style>
"""))

In [3]:
# enable all row display
# pd.set_option('display.max_rows', None)

Loading Top 20 Highest Selling SUV List

In [ ]:
# after loading it from .csv file it becomes a dataframe but we need it as a series 
# in rder to convert it back to a pandas series we need to make use of squeeze() function
# squeeze fucntion will work if the dataframe contains only one column as in this case
top_20_models_sales = (pd.read_csv('top_20_models_sales.csv', index_col = 0)).squeeze()

Processing Features Dataframe

In [4]:
all_car_features = []
all_car_prices = []
features_data_dir = './scraped_cardekho_top_20_models_features'
for file in os.listdir(features_data_dir):
    if file.endswith("features.csv"):
        # print('CURRENT FILE:', file)
        all_car_features.append(pd.read_csv(os.path.join(features_data_dir, file)))
    elif file.endswith("price.csv"):
        current_car_price = pd.read_csv(os.path.join(features_data_dir, file))
        car_details = file.split('-')
        current_car_price['company'] = car_details[0] # adding the company column to the price list
        current_car_price['model'] = car_details[1] # adding the model column to the price list
        current_car_price['variant'] = car_details[2][:-10] # adding the variant column to the price list
        all_car_prices.append(current_car_price)
features = pd.concat(all_car_features, ignore_index = True)
prices = pd.concat(all_car_prices, ignore_index = True)
print('All car features and prices combined')

All car features and prices combined

In [5]:
# saving the combined list of features into a file
features.to_csv(os.path.join(features_data_dir, 'all_car_features.csv'))
# saving the combined list of prices into a file
prices.to_csv(os.path.join(features_data_dir, 'all_car_prices.csv'))

In [6]:
features_data_dir = './scraped_cardekho_top_20_models_features'
features = pd.read_csv(os.path.join(features_data_dir, 'all_car_features.csv'))
prices = pd.read_csv(os.path.join(features_data_dir, 'all_car_prices.csv'))

In [7]:
features.describe()

,Unnamed: 0.13,Unnamed: 0.12,Unnamed: 0.11,Unnamed: 0.10,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0
count,919744.00000,854048.000000,788352.000000,722656.000000,656960.000000,591264.000000,525568.000000,459872.000000,394176.000000,328480.000000,262784.000000,197088.000000,131392.000000,65696.000000
mean,459871.50000,427023.500000,394175.500000,361327.500000,328479.500000,295631.500000,262783.500000,229935.500000,197087.500000,164239.500000,131391.500000,98543.500000,65695.500000,32847.500000
std,265507.36733,246542.565688,227577.764046,208612.962403,189648.160761,170683.359119,151718.557476,132753.755834,113788.954192,94824.152549,75859.350907,56894.549264,37929.747622,18964.945979
min,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,229935.75000,213511.750000,197087.750000,180663.750000,164239.750000,147815.750000,131391.750000,114967.750000,98543.750000,82119.750000,65695.750000,49271.750000,32847.750000,16423.750000
50%,459871.50000,427023.500000,394175.500000,361327.500000,328479.500000,295631.500000,262783.500000,229935.500000,197087.500000,164239.500000,131391.500000,98543.500000,65695.500000,32847.500000
75%,689807.25000,640535.250000,591263.250000,541991.250000,492719.250000,443447.250000,394175.250000,344903.250000,295631.250000,246359.250000,197087.250000,147815.250000,98543.250000,49271.250000
max,919743.00000,854047.000000,788351.000000,722655.000000,656959.000000,591263.000000,525567.000000,459871.000000,394175.000000,328479.000000,262783.000000,197087.000000,131391.000000,65695.000000

In [8]:
prices.describe()

        Unnamed: 0
count  5000.000000
mean   2499.500000
std    1443.520003
min       0.000000
25%    1249.750000
50%    2499.500000
75%    3749.250000
max    4999.000000

In [9]:
features.head()

,Unnamed: 0.13,company,model,variant,feature_name,feature_details,Unnamed: 0.12,Unnamed: 0.11,Unnamed: 0.10,Unnamed: 0.9,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0
0,0,mahindra,xuv300,XUV300 W4 Diesel BSVI,Engine Type,1.5L Turbo Diesel with CRDi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,mahindra,xuv300,XUV300 W4 Diesel BSVI,Displacement,1497 cc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,mahindra,xuv300,XUV300 W4 Diesel BSVI,Max Power,115.05bhp@3750rpm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,mahindra,xuv300,XUV300 W4 Diesel BSVI,Max Torque,300Nm@1500-2500rpm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,mahindra,xuv300,XUV300 W4 Diesel BSVI,No. of Cylinders,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
prices.head()

,Unnamed: 0,Ex-Showroom/ On-Road,Price,company,model,variant
0,0,Ex-Showroom Price,"Rs.9,14,890",TATA,NEXON,Nexon Smart Plus CNG
1,1,Bangalore,Rs.11.15 Lakh*,TATA,NEXON,Nexon Smart Plus CNG
2,2,Mumbai,Rs.10.25 Lakh*,TATA,NEXON,Nexon Smart Plus CNG
3,3,Pune,Rs.10.53 Lakh*,TATA,NEXON,Nexon Smart Plus CNG
4,4,Hyderabad,Rs.10.91 Lakh*,TATA,NEXON,Nexon Smart Plus CNG

In [11]:
features = features[['company', 'model', 'variant', 'feature_name', 'feature_details']]

In [12]:
# filtering out the top 20 models by sales
# features.loc[(features['model'].isin(top_20_models_sales.index.tolist()))]

In [13]:
features.describe()

,company,model,variant,feature_name,feature_details
count,919744,919744,919744,919744,919170
unique,8,22,500,261,773
top,HYUNDAI,CRETA,XUV300 W6 Diesel Sunroof BSVI,Additional Features,YES
freq,246190,135884,2800,12740,412300

In [14]:
features.model.unique()

array(['xuv300', 'CRETA', 'NEXON', 'BOLERO', 'GRAND VITARA', 'SELTOS',
       'VENUE', 'PUNCH', 'brezza', 'EXTER', 'CARENS', 'xuv700',
       'VITARA BREZZA', 'XL6', 'HYRYDER', 'S PRESSO', 'SONET', 'FRONX',
       'SCORPIO', 'xuv-3xo', 'THAR', 'ERTIGA'], dtype=object)

<!-- There are multiple ways to think about “relationship”: -->
	<!-- 1.	Is it linear? -->
	<!-- 2.	Is it monotonic (increasing/decreasing)? -->
	<!-- 3.	Is it nonlinear? -->
	<!-- 4.	Is it driven by outliers? -->
	<!-- 5.	Is it causal or just associated? -->
	<!-- 6.	Is length even meaningful, or just correlated with price/segment? -->

	1.	Scatter plot
	2.	Add regression line
	3.	Compute correlation 
	4.	Maybe add LOWESS smoothing if nonlinear

Processing 'prices' DataFrame

In [15]:
# trimming 'Rs.' from the beginning of each cell in the row 'Price'
prices['Price'] = prices['Price'].str[3:]

In [16]:
len(prices['model'].unique())

22

In [17]:
prices['Price_temp'] = prices['Price']

there are two types of format used in price_temp column:
1. for cities like mumbai, kolkata, delhi, etc. -> 'Rs.10.5 Lakh*'
2. for the Ex-Showroom Prices -> '10,50,000'
Both of these formats will be converted into -> '10.5'
For 1st 'Rs.' at the beginning and 'Lakh*' at the end have to be removed
For 2nd ',' have to removed and then the value has to be divided by 100000

In [18]:
# '10.5 Lakh*' -> '10.5' -> 'Lakh*' removed has been removed from the end
# '10,50,000' -> '1050000' -> ',' removed
prices['Price_temp'] = prices.apply(lambda row: row['Price'][:-5] if row['Price'][-5:] == "Lakh*" else row['Price'].replace(',', ''), axis = 1)

In [19]:
# converting the data type of Price_temp column from string to float
prices['Price_temp'] = prices['Price_temp'].astype('float')

In [20]:
# converting format for 'Ex-Showroom Price' rows
# 950000 -> 9.5
prices['Price_temp'] = prices.apply(lambda row: row['Price_temp'] / 100000  if row['Price'][-5:] != "Lakh*" else row['Price_temp'], axis = 1)

In [21]:
# droping the initial 'Price' column
prices = prices.drop(['Price'], axis = 1)

In [22]:
# renaming 'Price_temp' to 'price'
prices = prices.rename(columns={'Price_temp': 'price'})

In [23]:
prices.head()

,Unnamed: 0,Ex-Showroom/ On-Road,company,model,variant,price
0,0,Ex-Showroom Price,TATA,NEXON,Nexon Smart Plus CNG,9.1489
1,1,Bangalore,TATA,NEXON,Nexon Smart Plus CNG,11.1500
2,2,Mumbai,TATA,NEXON,Nexon Smart Plus CNG,10.2500
3,3,Pune,TATA,NEXON,Nexon Smart Plus CNG,10.5300
4,4,Hyderabad,TATA,NEXON,Nexon Smart Plus CNG,10.9100

In [24]:
(prices['model'].unique())

array(['NEXON', 'xuv300', 'GRAND VITARA', 'SONET', 'BOLERO', 'CRETA',
       'SELTOS', 'xuv_3xo', 'xuv700', 'brezza', 'FRONX', 'HYRYDER', 'XL6',
       'PUNCH', 'EXTER', 'VENUE', 'VITARA BREZZA', 'S PRESSO', 'CARENS',
       'SCORPIO', 'ERTIGA', 'THAR'], dtype=object)

In [25]:
prices['model'].unique()

array(['NEXON', 'xuv300', 'GRAND VITARA', 'SONET', 'BOLERO', 'CRETA',
       'SELTOS', 'xuv_3xo', 'xuv700', 'brezza', 'FRONX', 'HYRYDER', 'XL6',
       'PUNCH', 'EXTER', 'VENUE', 'VITARA BREZZA', 'S PRESSO', 'CARENS',
       'SCORPIO', 'ERTIGA', 'THAR'], dtype=object)

Pivot 'Features' Dataframes

In [26]:
features_pivot = features.pivot_table(
    index = ['company', 'model', 'variant'],
    columns = 'feature_name',
    values = 'feature_details',
    aggfunc='first'
)
features_pivot = features_pivot.reset_index()
features_pivot.to_csv('features_pivot.csv')
features_pivot

feature_name,company,model,variant,0-100Kmph (Tested),0-100kmph,360 View Camera,3rd Gear (30-80kmph),4th Gear (40-100kmph),Acceleration,Accessory Power Outlet,...,Ventilated Seats,Voice Commands,Voice assisted sunroof,Wheel Base,Wheel Covers,Wheel Size,Wi-Fi Connectivity,Width,Wireless Phone Charging,Xenon Headlamps
0,HYUNDAI,CRETA,Creta E,NaN,NaN,NO,NaN,NaN,NaN,YES,...,NO,NO,NO,2610 mm,YES,16 Inch,NaN,1790 mm,NO,NaN
1,HYUNDAI,CRETA,Creta E Diesel,NaN,NaN,NO,NaN,NaN,NaN,YES,...,NO,NO,NO,2610 mm,YES,16 Inch,NaN,1790 mm,NO,NaN
2,HYUNDAI,CRETA,Creta EX,NaN,NaN,NO,NaN,NaN,NaN,YES,...,NO,YES,NO,2610 mm,YES,16 Inch,NaN,1790 mm,NO,NaN
3,HYUNDAI,CRETA,Creta EX (O),NaN,NaN,NO,NaN,NaN,NaN,YES,...,NO,YES,NO,2610 mm,YES,16 Inch,NaN,1790 mm,NO,NaN
4,HYUNDAI,CRETA,Creta EX (O) Diesel,NaN,NaN,NO,NaN,NaN,NaN,YES,...,NO,YES,NO,2610 mm,YES,16 Inch,NaN,1790 mm,NO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,maruti,brezza,Brezza Zxi DT,NaN,NaN,NO,NaN,NaN,NaN,YES,...,NaN,NaN,NaN,2500 mm,NO,NaN,NaN,1790 mm,NO,NaN
496,maruti,brezza,Brezza Zxi Plus,NaN,NaN,YES,NaN,NaN,NaN,YES,...,NaN,NaN,NaN,2500 mm,NO,NaN,NaN,1790 mm,YES,NaN
497,maruti,brezza,Brezza Zxi Plus AT,15.24 s,NaN,YES,NaN,NaN,NaN,YES,...,NaN,NaN,NaN,2500 mm,NO,NaN,NaN,1790 mm,YES,NaN
498,maruti,brezza,Brezza Zxi Plus AT DT,15.24 s,NaN,YES,NaN,NaN,NaN,YES,...,NaN,NaN,NaN,2500 mm,NO,NaN,NaN,1790 mm,YES,NaN
499,maruti,brezza,Brezza Zxi Plus DT,NaN,NaN,YES,NaN,NaN,NaN,YES,...,NaN,NaN,NaN,2500 mm,NO,NaN,NaN,1790 mm,YES,NaN

In [27]:
features_pivot.columns.values

array(['company', 'model', 'variant', '0-100Kmph (Tested)', '0-100kmph',
       '360 View Camera', '3rd Gear (30-80kmph)', '4th Gear (40-100kmph)',
       'Acceleration', 'Accessory Power Outlet',
       'Active noise cancellation', 'Additional Features',
       'Adjustable Headlamps', 'Adjustable Headrest', 'Adjustable Seats',
       'Adjustable Steering', 'Air Conditioner', 'Air Quality Control',
       'Alloy Wheel Size', 'Alloy Wheel Size Front',
       'Alloy Wheel Size Rear', 'Alloy Wheels',
       'Ambient Light Colour (numbers)', 'Android Auto', 'Antenna',
       'Anti-Pinch Power Windows', 'Anti-Theft Alarm',
       'Anti-Theft Device', 'Anti-lock Braking System (ABS)',
       'Apple CarPlay', 'Approach Angle', 'Audio System Remote Control',
       'Automatic Climate Control', 'Automatic Headlamps',
       'Battery Saver', 'Bharat NCAP Child Safety Rating',
       'Bharat NCAP Safety Rating', 'Blind Spot Camera',
       'Bluetooth Connectivity', 'Boot Opening', 'Boot Space',
       'Brake Assist', 'Braking (100-0kmph)', 'Braking (60-0 kmph)',
       'Braking (80-0 kmph)', 'Break-over Angle',
       'CNG Fuel Tank Capacity', 'CNG Highway Mileage',
       'CNG Mileage ARAI', 'Central Console Armrest', 'Central Locking',
       'Centrally Mounted Fuel Tank', 'Child Safety Locks',
       'Chrome Garnish', 'Chrome Grille', 'Cigarette Lighter',
       'City driveability (20-80kmph)', 'Clutch Lock', 'Compass',
       'Connectivity', 'Convertible Top', 'Cooled Glovebox',
       'Cornering Foglamps', 'Cornering Headlamps', 'Crash Sensor',
       'Cruise Control', 'Cup Holders', 'Curtain Airbag',
       'Day & Night Rear View Mirror', 'Departure Angle',
       'Diesel Fuel Tank Capacity', 'Diesel Highway Mileage',
       'Diesel Mileage ARAI', 'Digital Clock', 'Digital Cluster',
       'Digital Cluster Size', 'Digital Odometer', 'Displacement',
       'Door Ajar Warning', 'Drive Mode Types', 'Drive Modes',
       'Drive Type', 'Driver Airbag', 'Driving Experience Control Eco',
       'Dual Tone Body Colour', 'Dual Tone Dashboard', 'EBD',
       'Electric Adjustable Seats',
       'Electronic Brakeforce Distribution (EBD)',
       'Electronic Multi-Tripmeter', 'Electronic Stability Control (ESC)',
       'Emission Norm Compliance', 'Engine Check Warning',
       'Engine Immobilizer', 'Engine Start/Stop Button', 'Engine Type',
       'Fabric Upholstery', 'Find My Car location', 'Fog Lights',
       'Fog Lights - Front', 'Fog Lights - Rear', 'Foldable Rear Seat',
       'Folding Table in The Rear', 'Follow Me Home Headlamps',
       'Front Brake Type', 'Front Impact Beams', 'Front Suspension',
       'Front Tread', 'Fuel Supply System', 'Fuel Type',
       'Gear Shift Indicator', 'Gearbox',
       'Global NCAP Child Safety Rating', 'Global NCAP Safety Rating',
       'Glove Box', 'Glove Box light', 'Gross Weight',
       'Ground Clearance Unladen', 'Halogen Headlamps',
       'Hands-Free Tailgate', 'Headlamp Washers',
       'Heads-Up Display (HUD)', 'Heated Outside Rear View Mirror',
       'Heated Wing Mirror', 'Heater', 'Height',
       'Height Adjustable Driver Seat',
       'Height Adjustable Front Seat Belts', 'Hill Assist',
       'Hill Descent Control', 'ISOFIX Child Seat Mounts',
       'Idle Start-Stop System', 'Impact Sensing Auto Door Unlock',
       'Inbuilt Apps', 'Integrated 2DIN Audio', 'Integrated Antenna',
       'Internal Storage', 'Kerb Weight', 'KeyLess Entry', 'Knee Airbags',
       'LED DRLs', 'LED Fog Lamps', 'LED Headlamps', 'LED Taillights',
       'Lane Change Indicator', 'Leather Seats',
       'Leather Wrapped Steering Wheel',
       'Leather wrap gear-shift selector', 'Length', 'Lighting',
       'Low Fuel Warning Light', 'Luggage Hook & Net', 'Lumbar Support',
       'Max Power', 'Max Torque', 'MirrorLink', 'Navigation System',
       'No. of Airbags', 'No. of Cylinders', 'No. of Doors',
       'No. of Speakers', 'Outside Rear View Mirror (ORVM)',
       'Outside Rear View Mirror Turn Indicators',
       'Outside Temperature Display', 'Paddle Shifters',
       'Parking Sensors', 'Passenger Airbag',
       'Passenger Side Rear View Mirror', 'Petrol Fuel Tank Capacity',
       'Petrol Fuel Tank Capacity (Litres)', 'Petrol Highway Mileage',
       'Petrol Mileage ARAI', 'Power Antenna', 'Power Boot',
       'Power Door Locks', 'Power Steering', 'Power Windows',
       'Pretensioners & Force Limiter Seatbelts', 'Projector Headlamps',
       'Puddle Lamps', 'Quarter Mile (Tested)', 'Radio',
       'Rain Sensing Wiper', 'Real-Time Vehicle Tracking',
       'Rear AC Vents', 'Rear Brake Type', 'Rear Camera', 'Rear Curtain',
       'Rear Entertainment System', 'Rear Reading Lamp',
       'Rear Seat Belts', 'Rear Seat Centre Arm Rest',
       'Rear Seat Headrest', 'Rear Spoiler', 'Rear Suspension',
       'Rear Touchscreen', 'Rear Tread', 'Rear Window Defogger',
       'Rear Window Sunblind', 'Rear Window Washer', 'Rear Window Wiper',
       'Rear Windscreen Sunblind', 'Regenerative Braking',
       'Remote Climate Control (A/C)', 'Remote Fuel Lid Opener',
       'Remote Trunk Opener', 'Reported Boot Space',
       'Reported Ground Clearance (Unladen)', 'Roof Carrier',
       'Roof Rails', 'Seat Belt Warning', 'Seating Capacity',
       'Secondary Fuel Type', 'Shock Absorbers Type', 'Side Airbag',
       'Side Airbag-Rear', 'Side Impact Beams', 'Side Stepper',
       'Smart Access Card Entry', 'Smart Key Band', 'Smoke Headlamps',
       'Speakers', 'Speed Alert', 'Speed Sensing Auto Door Lock',
       'Steering Column', 'Steering Gear Type', 'Steering Type',
       'Subwoofer', 'Sun Roof', 'Sunroof', 'Tachometer',
       'Tailgate Ajar Warning', 'Tinted Glass', 'Top Speed',
       'Touchscreen', 'Touchscreen Size', 'Traction Control',
       'Transmission Type', 'Trunk Light', 'Trunk Opener',
       'Turbo Charger', 'Turning Radius', 'Tweeters',
       'Tyre Pressure Monitoring System (TPMS)', 'Tyre Size', 'Tyre Type',
       'USB & Auxiliary input', 'USB Charger', 'Upholstery', 'Usb Ports',
       'Valve Configuration', 'Valves Per Cylinder', 'Vanity Mirror',
       'Vehicle Stability Control System', 'Ventilated Seats',
       'Voice Commands', 'Voice assisted sunroof', 'Wheel Base',
       'Wheel Covers', 'Wheel Size', 'Wi-Fi Connectivity', 'Width',
       'Wireless Phone Charging', 'Xenon Headlamps'], dtype=object)

In [28]:
len(features_pivot.columns)

264

List of Important Features

Other Features:
'360 View Camera',
'Active noise cancellation',
'Alloy Wheels',
'Anti-Theft Alarm',
'Automatic Climate Control',
'Automatic Headlamps',
'Blind Spot Camera',
'Ground Clearance Unladen',
'Hands-Free Tailgate',
'Heads-Up Display (HUD)',
'LED DRLs',
'Lumbar Support',
'Paddle Shifters',
'Power Boot',
'Real-Time Vehicle Tracking',
'Rain Sensing Wiper',
'Rear AC Vents',
'Rear Curtain',
'Rear Entertainment System',
'Rear Touchscreen',
'Rear Window Defogger',
'Rear Window Wiper',
'Remote Fuel Lid Opener',
'Remote Trunk Opener',
'Sun Roof',
'Sunroof',
'Tyre Size',
'Tyre Pressure Monitoring System (TPMS)',
'Ventilated Seats',
'Engine Immobilizer',


Essential Features:
'Connectivity',
'Apple CarPlay',
'Android Auto',
'Rear Camera',
'360 View Camera',
'Cruise Control',
'Power Windows',
'LED Fog Lamps', 
'LED Headlamps',
'Xenon Headlamps',
'Projector Headlamps',
'Fog Lights - Front',
'Fog Lights',
'Fog Lights - Front',
'Engine Start/Stop Button',
'KeyLess Entry',
'Traction Control',
'Hill Assist',
'Hill Descent Control',
'Halogen Headlamps',


Basics:
'CNG Highway Mileage',
'CNG Mileage ARAI',
'Child Safety Locks',
'Connectivity',
'Apple CarPlay',
'Diesel Highway Mileage',
'Drive Type',
'Fuel Type',
'Gearbox',
'Length',
'No. of Cylinders',
'Transmission Type',
'Displacement',
'Seating Capacity',


Safety:
'Bharat NCAP Child Safety Rating',
'Bharat NCAP Safety Rating', 
'Global NCAP Child Safety Rating',
'Global NCAP Safety Rating',
'Child Safety Locks',
'Curtain Airbag',
'EBD',
'Electronic Brakeforce Distribution (EBD)',
'Electronic Stability Control (ESC)',
'Front Impact Beams',
'Impact Sensing Auto Door Unlock',
'Knee Airbags',
'No. of Airbags',
'Passenger Airbag',
'Petrol Highway Mileage',
'Petrol Mileage ARAI', 
'Side Airbag',
'Side Airbag-Rear',
'Side Impact Beams',
'Vehicle Stability Control System'

Delete the irrelevant features

In [29]:
features_pivot = features_pivot[['company', 'model', 'variant', '360 View Camera',
    'Active noise cancellation',
    'Alloy Wheels',
    'Anti-Theft Alarm',
    'Automatic Climate Control',
    'Automatic Headlamps',
    'Blind Spot Camera',
    'Cruise Control',
    'Drive Modes',
    'Engine Start/Stop Button',
    'Fog Lights - Front',
    'Fog Lights',
    'Fog Lights - Front',
    'Ground Clearance Unladen',
    'Halogen Headlamps',
    'Hands-Free Tailgate',
    'Heads-Up Display (HUD)',
    'Hill Assist',
    'Hill Descent Control',
    'KeyLess Entry',
    'LED DRLs',
    'LED Fog Lamps', 
    'LED Headlamps',
    'Lumbar Support',
    'Paddle Shifters',
    'Power Boot',
    'Real-Time Vehicle Tracking',
    'Rain Sensing Wiper',
    'Rear AC Vents',
    'Rear Camera',
    'Rear Curtain',
    'Rear Entertainment System',
    'Rear Touchscreen',
    'Rear Window Defogger',
    'Rear Window Wiper',
    'Remote Fuel Lid Opener',
    'Remote Trunk Opener',
    'Seating Capacity',
    'Traction Control',
    'Sun Roof',
    'Sunroof',
    'Projector Headlamps',
    'Tyre Size',
    'Tyre Pressure Monitoring System (TPMS)',
    'Ventilated Seats',
    'Xenon Headlamps',
    'Engine Immobilizer',
    'Power Windows',
    'Connectivity',
    'Apple CarPlay',
    'Android Auto',
    'CNG Highway Mileage',
    'CNG Mileage ARAI',
    'Child Safety Locks',
    'Connectivity',
    'Apple CarPlay',
    'Diesel Highway Mileage',
    'Drive Type',
    'Fuel Type',
    'Gearbox',
    'Length',
    'No. of Cylinders',
    'Transmission Type',
    'Displacement',
    'Bharat NCAP Child Safety Rating',
    'Bharat NCAP Safety Rating', 
    'Global NCAP Child Safety Rating',
    'Global NCAP Safety Rating',
    'Child Safety Locks',
    'Curtain Airbag',
    'EBD',
    'Electronic Brakeforce Distribution (EBD)',
    'Electronic Stability Control (ESC)',
    'Front Impact Beams',
    'Impact Sensing Auto Door Unlock',
    'Knee Airbags',
    'No. of Airbags',
    'Passenger Airbag',
    'Petrol Highway Mileage',
    'Petrol Mileage ARAI',
    'Petrol Highway Mileage',
    'Diesel Mileage ARAI',
    'Side Airbag',
    'Side Airbag-Rear',
    'Side Impact Beams',
    'Vehicle Stability Control System'
]]

In [30]:
len(features_pivot.columns)

89

In [31]:
# features_pivot[(features_pivot['Side Airbag'] == 'Yes')]
features_pivot.head()

feature_name,company,model,variant,360 View Camera,Active noise cancellation,Alloy Wheels,Anti-Theft Alarm,Automatic Climate Control,Automatic Headlamps,Blind Spot Camera,...,No. of Airbags,Passenger Airbag,Petrol Highway Mileage,Petrol Mileage ARAI,Petrol Highway Mileage,Diesel Mileage ARAI,Side Airbag,Side Airbag-Rear,Side Impact Beams,Vehicle Stability Control System
0,HYUNDAI,CRETA,Creta E,NO,NaN,NO,YES,NO,NO,NaN,...,6,YES,NaN,17.4 kmpl,NaN,NaN,YES,NO,NaN,NaN
1,HYUNDAI,CRETA,Creta E Diesel,NO,NaN,NO,YES,NO,NO,NaN,...,6,YES,NaN,NaN,NaN,21.8 kmpl,YES,NO,NaN,NaN
2,HYUNDAI,CRETA,Creta EX,NO,NaN,NO,YES,NO,NO,NaN,...,6,YES,NaN,17.4 kmpl,NaN,NaN,YES,NO,NaN,NaN
3,HYUNDAI,CRETA,Creta EX (O),NO,NaN,NO,YES,YES,NO,NaN,...,6,YES,NaN,17.4 kmpl,NaN,NaN,YES,NO,NaN,NaN
4,HYUNDAI,CRETA,Creta EX (O) Diesel,NO,NaN,NO,YES,NO,NO,NaN,...,6,YES,NaN,NaN,NaN,21.8 kmpl,YES,NO,NaN,NaN

Prepare 'Prices' and Merger with 'Features'

In [32]:
prices.head()

,Unnamed: 0,Ex-Showroom/ On-Road,company,model,variant,price
0,0,Ex-Showroom Price,TATA,NEXON,Nexon Smart Plus CNG,9.1489
1,1,Bangalore,TATA,NEXON,Nexon Smart Plus CNG,11.1500
2,2,Mumbai,TATA,NEXON,Nexon Smart Plus CNG,10.2500
3,3,Pune,TATA,NEXON,Nexon Smart Plus CNG,10.5300
4,4,Hyderabad,TATA,NEXON,Nexon Smart Plus CNG,10.9100

In [33]:
# len(prices['model'].unique())

In [34]:
# prices['model'].unique()

In [35]:
# removing the rows for 'Ex-Showroom Price'
prices = prices[(prices['Ex-Showroom/ On-Road'] != 'Ex-Showroom Price')]

In [36]:
# prices_mean = prices.groupby(['model'])['price'].mean()

In [37]:
# prices_mean

In [38]:
# len(features_pivot['model'].unique())

In [39]:
features_pivot.loc[(features_pivot['model'] == 'xuv300'), 'model'] = 'XUV 300'
features_pivot.loc[(features_pivot['model'] == 'xuv-3xo'), 'model'] = 'XUV 300'
features_pivot.loc[(features_pivot['model'] == 'brezza'), 'model'] = 'VITARA BREZZA'
features_pivot.loc[(features_pivot['model'] == 'xuv700'), 'model'] = 'XUV 700'

In [40]:
prices.loc[(prices['model'] == 'xuv300'), 'model'] = 'xuv_3xo'
prices.loc[(prices['model'] == 'xuv-3xo'), 'model'] = 'xuv_3xo'
prices.loc[(prices['model'] == 'brezza'), 'model'] = 'VITARA BREZZA'
prices.loc[(prices['model'] == 'xuv700'), 'model'] = 'XUV 700'

In [41]:
# modifying variant
features_pivot['variant'] = features_pivot['variant'].str.replace('-', ' ')
prices['variant'] = prices['variant'].str.replace('-', ' ')

/var/folders/_7/8mmqgn7s4bjc8l8cr6llqzq80000gn/T/ipykernel_77234/2185400671.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features_pivot['variant'] = features_pivot['variant'].str.replace('-', ' ')

In [42]:
# features_pivot['variant'] = features_pivot.apply(
#     lambda row: row['variant'].replace(row['model'], '').strip(), axis=1
# )

In [43]:
# prices['variant'] = prices.apply(
#     lambda row: row['variant'].replace(row['model'], '').strip(), axis=1
# )

In [44]:
len(features_pivot['model'].unique())

20

In [45]:
len(features_pivot['model'].unique())

20

In [46]:
features_pivot['model'].unique()

array(['CRETA', 'EXTER', 'VENUE', 'CARENS', 'SELTOS', 'SONET', 'BOLERO',
       'SCORPIO', 'THAR', 'ERTIGA', 'FRONX', 'GRAND VITARA', 'S PRESSO',
       'VITARA BREZZA', 'XL6', 'NEXON', 'PUNCH', 'HYRYDER', 'XUV 300',
       'XUV 700'], dtype=object)

In [47]:
prices['model'].unique()

array(['NEXON', 'GRAND VITARA', 'SONET', 'BOLERO', 'CRETA', 'SELTOS',
       'xuv_3xo', 'XUV 700', 'VITARA BREZZA', 'FRONX', 'HYRYDER', 'XL6',
       'PUNCH', 'EXTER', 'VENUE', 'S PRESSO', 'CARENS', 'SCORPIO',
       'ERTIGA', 'THAR'], dtype=object)

In [48]:
# root_dir = "/Users/soumadittya/code/suv-analysis/output_cardekho_top_20_models/"
# for file in os.listdir(root_dir):
#     # print(file)
#     if 'xuv-3xo' in file:
#         print("CURRENT FILE:", file)
#         os.rename(os.path.join(root_dir, file), os.path.join(root_dir, file.replace('xuv-3xo', 'xuv_3xo')))

In [49]:
prices.columns

Index(['Unnamed: 0', 'Ex-Showroom/ On-Road', 'company', 'model', 'variant',
       'price'],
      dtype='object')

In [50]:
prices['price_start'] = prices.groupby('model')['price'].transform('min')
prices['price_max'] = prices.groupby('model')['price'].transform('max')
prices['price_avg'] = prices.groupby('model')['price'].transform('mean')

In [51]:
# printing the merged results but not assigning it to variables
(pd.merge(features_pivot, prices[['variant', 'price_start', 'price_avg', 'price_max']], how = 'left', on = 'variant')).to_csv('combined.csv')

In [52]:
# features_prices = pd.merge(features_pivot, prices[['company', 'model', 'variant', 'price']], how = 'left', on = 'variant')
features_prices = pd.merge(features_pivot, prices[['variant', 'price_start', 'price_avg', 'price_max']], how = 'left', on = 'variant')

Adding 'Sales' Column

In [53]:
# creating a new column 'sales'
features_prices['sales'] = features_prices['model'].map(top_20_models_sales)

Removing Duplicates from 'Variants'

In [54]:
features_prices = features_prices.drop_duplicates(subset='variant')

In [55]:
features_prices.head(2)

,company,model,variant,360 View Camera,Active noise cancellation,Alloy Wheels,Anti-Theft Alarm,Automatic Climate Control,Automatic Headlamps,Blind Spot Camera,...,Petrol Highway Mileage,Diesel Mileage ARAI,Side Airbag,Side Airbag-Rear,Side Impact Beams,Vehicle Stability Control System,price_start,price_avg,price_max,sales
0,HYUNDAI,CRETA,Creta E,NO,NaN,NO,YES,NO,NO,NaN,...,NaN,NaN,YES,NO,NaN,NaN,12.07,20.1021,25.44,626200.0
10,HYUNDAI,CRETA,Creta E Diesel,NO,NaN,NO,YES,NO,NO,NaN,...,NaN,21.8 kmpl,YES,NO,NaN,NaN,12.07,20.1021,25.44,626200.0

In [56]:
features_prices.to_csv('features_prices.csv')

Load 'features_prices' Dataset

In [57]:
features_prices = pd.read_csv('features_prices.csv')

In [58]:
features_prices.columns

Index(['Unnamed: 0', 'company', 'model', 'variant', '360 View Camera',
       'Active noise cancellation', 'Alloy Wheels', 'Anti-Theft Alarm',
       'Automatic Climate Control', 'Automatic Headlamps', 'Blind Spot Camera',
       'Cruise Control', 'Drive Modes', 'Engine Start/Stop Button',
       'Fog Lights - Front', 'Fog Lights', 'Fog Lights - Front.1',
       'Ground Clearance Unladen', 'Halogen Headlamps', 'Hands-Free Tailgate',
       'Heads-Up Display (HUD)', 'Hill Assist', 'Hill Descent Control',
       'KeyLess Entry', 'LED DRLs', 'LED Fog Lamps', 'LED Headlamps',
       'Lumbar Support', 'Paddle Shifters', 'Power Boot',
       'Real-Time Vehicle Tracking', 'Rain Sensing Wiper', 'Rear AC Vents',
       'Rear Camera', 'Rear Curtain', 'Rear Entertainment System',
       'Rear Touchscreen', 'Rear Window Defogger', 'Rear Window Wiper',
       'Remote Fuel Lid Opener', 'Remote Trunk Opener', 'Seating Capacity',
       'Traction Control', 'Sun Roof', 'Sunroof', 'Projector Headlamps',
       'Tyre Size', 'Tyre Pressure Monitoring System (TPMS)',
       'Ventilated Seats', 'Xenon Headlamps', 'Engine Immobilizer',
       'Power Windows', 'Connectivity', 'Apple CarPlay', 'Android Auto',
       'CNG Highway Mileage', 'CNG Mileage ARAI', 'Child Safety Locks',
       'Connectivity.1', 'Apple CarPlay.1', 'Diesel Highway Mileage',
       'Drive Type', 'Fuel Type', 'Gearbox', 'Length', 'No. of Cylinders',
       'Transmission Type', 'Displacement', 'Bharat NCAP Child Safety Rating',
       'Bharat NCAP Safety Rating', 'Global NCAP Child Safety Rating',
       'Global NCAP Safety Rating', 'Child Safety Locks.1', 'Curtain Airbag',
       'EBD', 'Electronic Brakeforce Distribution (EBD)',
       'Electronic Stability Control (ESC)', 'Front Impact Beams',
       'Impact Sensing Auto Door Unlock', 'Knee Airbags', 'No. of Airbags',
       'Passenger Airbag', 'Petrol Highway Mileage', 'Petrol Mileage ARAI',
       'Petrol Highway Mileage.1', 'Diesel Mileage ARAI', 'Side Airbag',
       'Side Airbag-Rear', 'Side Impact Beams',
       'Vehicle Stability Control System', 'price_start', 'price_avg',
       'price_max', 'sales'],
      dtype='object')

In [59]:
# length of feature prices
len(features_prices)

500

Safety

In [60]:
safety = features_prices[['company', 'model', 'variant', 'price_start', 'price_avg', 'price_max', 'sales', 'Bharat NCAP Child Safety Rating', 'Bharat NCAP Safety Rating', 'Global NCAP Child Safety Rating', 'Global NCAP Safety Rating', 'Child Safety Locks', 'Curtain Airbag', 'EBD', 'Electronic Brakeforce Distribution (EBD)', 'Electronic Stability Control (ESC)', 'Front Impact Beams', 'Impact Sensing Auto Door Unlock', 'Knee Airbags', 'No. of Airbags', 'Passenger Airbag', 'Side Airbag', 'Side Airbag-Rear', 'Side Impact Beams', 'Vehicle Stability Control System']]
safety.head(2)

,company,model,variant,price_start,price_avg,price_max,sales,Bharat NCAP Child Safety Rating,Bharat NCAP Safety Rating,Global NCAP Child Safety Rating,...,Electronic Stability Control (ESC),Front Impact Beams,Impact Sensing Auto Door Unlock,Knee Airbags,No. of Airbags,Passenger Airbag,Side Airbag,Side Airbag-Rear,Side Impact Beams,Vehicle Stability Control System
0,HYUNDAI,CRETA,Creta E,12.07,20.1021,25.44,626200.0,NaN,NaN,3 Star,...,YES,NaN,YES,NO,6,YES,YES,NO,NaN,NaN
1,HYUNDAI,CRETA,Creta E Diesel,12.07,20.1021,25.44,626200.0,NaN,NaN,NaN,...,YES,NaN,YES,NO,6,YES,YES,NO,NaN,NaN

In [61]:
safety.to_csv('safety.csv')

Specifications

In [62]:
specifications = features_prices[['company', 'model', 'variant', 'price_start', 'price_avg', 'price_max', 'sales', 'CNG Highway Mileage', 'CNG Mileage ARAI', 'Child Safety Locks', 'Connectivity', 'Apple CarPlay', 'Diesel Highway Mileage', 'Diesel Mileage ARAI', 'Petrol Highway Mileage', 'Petrol Mileage ARAI', 'Drive Type', 'Fuel Type', 'Gearbox', 'Length', 'No. of Cylinders', 'Transmission Type', 'Displacement']]
specifications.head(2)

,company,model,variant,price_start,price_avg,price_max,sales,CNG Highway Mileage,CNG Mileage ARAI,Child Safety Locks,...,Diesel Mileage ARAI,Petrol Highway Mileage,Petrol Mileage ARAI,Drive Type,Fuel Type,Gearbox,Length,No. of Cylinders,Transmission Type,Displacement
0,HYUNDAI,CRETA,Creta E,12.07,20.1021,25.44,626200.0,NaN,NaN,YES,...,NaN,NaN,17.4 kmpl,FWD,Petrol,6-Speed,4330 mm,4,Manual,1497 cc
1,HYUNDAI,CRETA,Creta E Diesel,12.07,20.1021,25.44,626200.0,NaN,NaN,YES,...,21.8 kmpl,NaN,NaN,FWD,Diesel,6-Speed,4330 mm,4,Manual,1493 cc

In [63]:
specifications.to_csv('specifications.csv')

Essential Features

In [64]:
essentials = features_prices[['company', 'model', 'variant', 'price_start', 'price_avg', 'price_max', 'sales', 'Connectivity', 'Apple CarPlay', 'Android Auto', 'Rear Camera', '360 View Camera', 'Cruise Control', 'Power Windows', 'LED Fog Lamps', 'LED Headlamps', 'Xenon Headlamps', 'Projector Headlamps', 'Fog Lights - Front', 'Fog Lights', 'Fog Lights - Front', 'Engine Start/Stop Button', 'KeyLess Entry', 'Traction Control', 'Hill Assist', 'Hill Descent Control', 'Halogen Headlamps']]
essentials.head(2)

,company,model,variant,price_start,price_avg,price_max,sales,Connectivity,Apple CarPlay,Android Auto,...,Projector Headlamps,Fog Lights - Front,Fog Lights,Fog Lights - Front,Engine Start/Stop Button,KeyLess Entry,Traction Control,Hill Assist,Hill Descent Control,Halogen Headlamps
0,HYUNDAI,CRETA,Creta E,12.07,20.1021,25.44,626200.0,NaN,NO,NO,...,YES,NaN,NaN,NaN,NO,YES,NO,YES,NaN,NaN
1,HYUNDAI,CRETA,Creta E Diesel,12.07,20.1021,25.44,626200.0,NaN,NO,NO,...,YES,NaN,NaN,NaN,NO,YES,NO,YES,NaN,NaN

In [65]:
essentials.to_csv('essentials.csv')

Other Features

In [66]:
others = features_prices[['company', 'model', 'variant', 'price_start', 'price_avg', 'price_max', 'sales', '360 View Camera', 'Active noise cancellation', 'Alloy Wheels', 'Anti-Theft Alarm', 'Automatic Climate Control', 'Automatic Headlamps', 'Blind Spot Camera', 'Ground Clearance Unladen', 'Hands-Free Tailgate', 'Heads-Up Display (HUD)', 'LED DRLs', 'Lumbar Support', 'Paddle Shifters', 'Power Boot', 'Real-Time Vehicle Tracking', 'Rain Sensing Wiper', 'Rear AC Vents', 'Rear Curtain', 'Rear Entertainment System', 'Rear Touchscreen', 'Rear Window Defogger', 'Rear Window Wiper', 'Remote Fuel Lid Opener', 'Remote Trunk Opener', 'Sun Roof', 'Sunroof', 'Tyre Size', 'Tyre Pressure Monitoring System (TPMS)', 'Ventilated Seats', 'Engine Immobilizer']]
others.head(2)

,company,model,variant,price_start,price_avg,price_max,sales,360 View Camera,Active noise cancellation,Alloy Wheels,...,Rear Window Defogger,Rear Window Wiper,Remote Fuel Lid Opener,Remote Trunk Opener,Sun Roof,Sunroof,Tyre Size,Tyre Pressure Monitoring System (TPMS),Ventilated Seats,Engine Immobilizer
0,HYUNDAI,CRETA,Creta E,12.07,20.1021,25.44,626200.0,NO,NaN,NO,...,NO,NO,NaN,NaN,NaN,NO,205/65 R16,YES,NO,YES
1,HYUNDAI,CRETA,Creta E Diesel,12.07,20.1021,25.44,626200.0,NO,NaN,NO,...,NO,NO,NaN,NaN,NaN,NO,205/65 R16,YES,NO,YES

In [67]:
others.to_csv('others.csv')